name: install deps
on: [push]
jobs:
  prepare:
    name: Installing dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

  install:
    name: Install dependencies
    steps:
      uses: borales/actions-yarn@v4
      with:
        cmd: install

  prettier:
    name: Prettier
    steps:
      uses: borales/actions-yarn@v4
      with:
        cmd: prettify

  linting:
    name: ESLint
    steps:
      uses: borales/actions-yarn@v4
      with:
        cmd: lint

  build:
    name: Build
    steps:
      uses: borales/actions-yarn@v4
      with:
        cmd: build
