name: Workflow
run-name: ${{ github.actor }} is running workflow
on: [push]
jobs:
  prepare:
    name: Installing dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        id: repository-code
        uses: actions/checkout@v3

      - name: Get yarn cache director path
        id: cache-dir
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache installing deps
        uses: actions/cache@v3
        with:
          path: ${{ steps.cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Get yarn cache director path
        id: cache-dir
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache installing deps
        uses: actions/cache@v3
        with:
          path: ${{ steps.cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - uses: borales/actions-yarn@v4
        with:
          cmd: prettify

  lint:
    name: ESLint
    runs-on: ubuntu-latest
    needs: prettier
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Get yarn cache director path
        id: cache-dir
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache installing deps
        uses: actions/cache@v3
        with:
          path: ${{ steps.cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - uses: borales/actions-yarn@v4
        with:
          cmd: lint

  build:
    name: Build
    needs: lint
    continue-on-error: true
    strategy:
      matrix:
        node-version: [14, 16, 18]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache director path
        id: cache-dir
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache installing deps
        uses: actions/cache@v3
        with:
          path: ${{ steps.cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: UploadArtifacts
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build-files

  artifacts:
    name: Artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build
        uses: actions/download-artifact@v3
        with:
          name: build-files
