name: install deps
run-name: ${{ github.actor }} is running workflow
on: [push]
jobs:
  prepare:
    name: Installing dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - uses: borales/actions-yarn@v4
        with:
          cmd: prettify

  lint:
    name: ESLint
    runs-on: ubuntu-latest
    needs: prettier
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - uses: borales/actions-yarn@v4
        with:
          cmd: lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - uses: borales/actions-yarn@v4
        with:
          cmd: build
