name: github-actions-workflow
on: push
jobs:
  prepare:
    name: Install deps
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install deps
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ github.run_id }}}
          restore-keys: ${{ runner.os }}-yarn

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Get cached deps
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ github.run_id }}}
          restore-keys: ${{ runner.os }}-yarn

      - name: Prettify
        uses: borales/actions-yarn@v4
        with:
          cmd: prettify
