name: github-actions-workflow
on: workflow_dispatch
jobs:
  prepare:
    name: Install deps
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install deps
        uses: borales/actions-yarn@v4
        with:
          cmd: install

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Prettify
        uses: borales/actions-yarn@v4
        with:
          cmd: prettify
